total_number: 12
list:
  - id: 3
    type: 1
    pose: [2, 15.5, 0]
    radius_speed_accel: [1.2, 0.2, 0.5]
    map_name: conveyor_map
    localizer_main_sub: [1, 0]
    storage_level_unload_load:
      - [100, 100]
  - id: 4
    type: 0
    pose: [6.3, 15.507, 0]
    radius_speed_accel: [0.8, 0.5, 0.5]
    map_name: conveyor_map
    localizer_main_sub: [1, 0]
    storage_level_unload_load:
      - [100, 100]
  - id: 5
    type: 0
    pose: [6.3, 6, 0]
    radius_speed_accel: [0.8, 0.5, 0.5]
    map_name: conveyor_map
    localizer_main_sub: [1, 0]
    storage_level_unload_load:
      - [100, 100]
  - id: 10
    type: 0
    pose: [2, 6, 0]
    radius_speed_accel: [0.8, 0.5, 0.5]
    map_name: conveyor_map
    localizer_main_sub: [1, 0]
    storage_level_unload_load:
      - [100, 100]
  - id: 11
    type: 0
    pose: [6.3, 9, 0]
    radius_speed_accel: [0.8, 0.5, 0.5]
    map_name: conveyor_map
    localizer_main_sub: [1, 0]
    storage_level_unload_load:
      - [100, 100]
  - id: 13
    type: 0
    pose: [2, 12.2, 0]
    radius_speed_accel: [0.8, 0.5, 0.5]
    map_name: conveyor_map
    localizer_main_sub: [1, 0]
    storage_level_unload_load:
      - [100, 100]
  - id: 14
    type: 0
    pose: [2, 9, 0]
    radius_speed_accel: [0.8, 0.5, 0.5]
    map_name: conveyor_map
    localizer_main_sub: [1, 0]
    storage_level_unload_load:
      - [100, 100]
  - id: 15
    type: 1
    pose: [4.161, 6, 0]
    radius_speed_accel: [0.8, 0.5, 0.5]
    map_name: conveyor_map
    localizer_main_sub: [1, 0]
    storage_level_unload_load:
      - [100, 100]
  - id: 16
    type: 0
    pose: [4.223, 15.5, 0]
    radius_speed_accel: [0.8, 0.5, 0.5]
    map_name: conveyor_map
    localizer_main_sub: [1, 0]
    storage_level_unload_load:
      - [100, 100]
  - id: 17
    type: 0
    pose: [4.247, 12.2, 0]
    radius_speed_accel: [0.8, 0.5, 0.5]
    map_name: conveyor_map
    localizer_main_sub: [1, 0]
    storage_level_unload_load:
      - [100, 100]
  - id: 18
    type: 0
    pose: [4.213, 9, 0]
    radius_speed_accel: [0.8, 0.5, 0.5]
    map_name: conveyor_map
    localizer_main_sub: [1, 0]
    storage_level_unload_load:
      - [100, 100]
  - id: 19
    type: 2
    pose: [3.616, 10.666, 0]
    radius_speed_accel: [0.8, 0.5, 0.5]
    map_name: conveyor_map
    localizer_main_sub: [1, 0]
    storage_level_unload_load:
      - [100, 100]
