total_number: 62
list:
  - id: 101
    type: 0
    pose: [2, 22, 0]
    radius_speed_accel: [1, 1, 1]
    map_name: conveyor_map
    localizer_main_sub: [1, 0]
    storage_level_unload_load:
      - [100, 100]
  - id: 102
    type: 0
    pose: [5, 22, 0]
    radius_speed_accel: [1, 1, 1]
    map_name: conveyor_map
    localizer_main_sub: [1, 0]
    storage_level_unload_load:
      - [100, 100]
  - id: 103
    type: 0
    pose: [9, 22, 0]
    radius_speed_accel: [1, 1, 1]
    map_name: conveyor_map
    localizer_main_sub: [1, 0]
    storage_level_unload_load:
      - [100, 100]
  - id: 104
    type: 0
    pose: [9.5, 22.5, 0]
    radius_speed_accel: [1, 1, 1]
    map_name: conveyor_map
    localizer_main_sub: [1, 0]
    storage_level_unload_load:
      - [100, 100]
  - id: 105
    type: 0
    pose: [10, 23, 0]
    radius_speed_accel: [1, 1, 1]
    map_name: conveyor_map
    localizer_main_sub: [1, 0]
    storage_level_unload_load:
      - [100, 100]
  - id: 106
    type: 0
    pose: [11.5, 24.5, 0]
    radius_speed_accel: [1, 1, 1]
    map_name: conveyor_map
    localizer_main_sub: [1, 0]
    storage_level_unload_load:
      - [100, 100]
  - id: 107
    type: 0
    pose: [13, 26, 0]
    radius_speed_accel: [1, 1, 1]
    map_name: conveyor_map
    localizer_main_sub: [1, 0]
    storage_level_unload_load:
      - [100, 100]
  - id: 108
    type: 0
    pose: [13.5, 26.5, 0]
    radius_speed_accel: [1, 1, 1]
    map_name: conveyor_map
    localizer_main_sub: [1, 0]
    storage_level_unload_load:
      - [100, 100]
  - id: 109
    type: 0
    pose: [14, 27, 0]
    radius_speed_accel: [1, 1, 1]
    map_name: conveyor_map
    localizer_main_sub: [1, 0]
    storage_level_unload_load:
      - [100, 100]
  - id: 110
    type: 0
    pose: [14, 22, 0]
    radius_speed_accel: [1, 1, 1]
    map_name: conveyor_map
    localizer_main_sub: [1, 0]
    storage_level_unload_load:
      - [100, 100]
  - id: 111
    type: 0
    pose: [14.5, 17.5, 0]
    radius_speed_accel: [1, 1, 1]
    map_name: conveyor_map
    localizer_main_sub: [1, 0]
    storage_level_unload_load:
      - [100, 100]
  - id: 112
    type: 0
    pose: [15, 18, 0]
    radius_speed_accel: [1, 1, 1]
    map_name: conveyor_map
    localizer_main_sub: [1, 0]
    storage_level_unload_load:
      - [100, 100]
  - id: 113
    type: 0
    pose: [16.5, 19.5, 0]
    radius_speed_accel: [1, 1, 1]
    map_name: conveyor_map
    localizer_main_sub: [1, 0]
    storage_level_unload_load:
      - [100, 100]
  - id: 114
    type: 0
    pose: [18, 21, 0]
    radius_speed_accel: [1, 1, 1]
    map_name: conveyor_map
    localizer_main_sub: [1, 0]
    storage_level_unload_load:
      - [100, 100]
  - id: 115
    type: 0
    pose: [18.5, 21.5, 0]
    radius_speed_accel: [1, 1, 1]
    map_name: conveyor_map
    localizer_main_sub: [1, 0]
    storage_level_unload_load:
      - [100, 100]
  - id: 116
    type: 0
    pose: [19, 22, 0]
    radius_speed_accel: [1, 1, 1]
    map_name: conveyor_map
    localizer_main_sub: [1, 0]
    storage_level_unload_load:
      - [100, 100]
  - id: 117
    type: 0
    pose: [19, 22.5, 0]
    radius_speed_accel: [1, 1, 1]
    map_name: conveyor_map
    localizer_main_sub: [1, 0]
    storage_level_unload_load:
      - [100, 100]
  - id: 118
    type: 0
    pose: [19, 23, 0]
    radius_speed_accel: [1, 1, 1]
    map_name: conveyor_map
    localizer_main_sub: [1, 0]
    storage_level_unload_load:
      - [100, 100]
  - id: 119
    type: 0
    pose: [19, 24.5, 0]
    radius_speed_accel: [1, 1, 1]
    map_name: conveyor_map
    localizer_main_sub: [1, 0]
    storage_level_unload_load:
      - [100, 100]
  - id: 120
    type: 0
    pose: [19, 26, 0]
    radius_speed_accel: [1, 1, 1]
    map_name: conveyor_map
    localizer_main_sub: [1, 0]
    storage_level_unload_load:
      - [100, 100]
  - id: 121
    type: 0
    pose: [19, 26.5, 0]
    radius_speed_accel: [1, 1, 1]
    map_name: conveyor_map
    localizer_main_sub: [1, 0]
    storage_level_unload_load:
      - [100, 100]
  - id: 122
    type: 0
    pose: [19, 27, 0]
    radius_speed_accel: [1, 1, 1]
    map_name: conveyor_map
    localizer_main_sub: [1, 0]
    storage_level_unload_load:
      - [100, 100]
  - id: 123
    type: 0
    pose: [24, 17.5, 0]
    radius_speed_accel: [1, 1, 1]
    map_name: conveyor_map
    localizer_main_sub: [1, 0]
    storage_level_unload_load:
      - [100, 100]
  - id: 124
    type: 0
    pose: [24, 18, 0]
    radius_speed_accel: [1, 1, 1]
    map_name: conveyor_map
    localizer_main_sub: [1, 0]
    storage_level_unload_load:
      - [100, 100]
  - id: 125
    type: 0
    pose: [24, 19.5, 0]
    radius_speed_accel: [1, 1, 1]
    map_name: conveyor_map
    localizer_main_sub: [1, 0]
    storage_level_unload_load:
      - [100, 100]
  - id: 126
    type: 0
    pose: [24, 21, 0]
    radius_speed_accel: [1, 1, 1]
    map_name: conveyor_map
    localizer_main_sub: [1, 0]
    storage_level_unload_load:
      - [100, 100]
  - id: 127
    type: 0
    pose: [24, 21.5, 0]
    radius_speed_accel: [1, 1, 1]
    map_name: conveyor_map
    localizer_main_sub: [1, 0]
    storage_level_unload_load:
      - [100, 100]
  - id: 128
    type: 0
    pose: [24, 22, 0]
    radius_speed_accel: [1, 1, 1]
    map_name: conveyor_map
    localizer_main_sub: [1, 0]
    storage_level_unload_load:
      - [100, 100]
  - id: 129
    type: 0
    pose: [24, 27, 0]
    radius_speed_accel: [1, 1, 1]
    map_name: conveyor_map
    localizer_main_sub: [1, 0]
    storage_level_unload_load:
      - [100, 100]
  - id: 130
    type: 0
    pose: [29, 22, 0]
    radius_speed_accel: [1, 1, 1]
    map_name: conveyor_map
    localizer_main_sub: [1, 0]
    storage_level_unload_load:
      - [100, 100]
  - id: 131
    type: 0
    pose: [32, 22, 0]
    radius_speed_accel: [1, 1, 1]
    map_name: conveyor_map
    localizer_main_sub: [1, 0]
    storage_level_unload_load:
      - [100, 100]
  - id: 201
    type: 0
    pose: [32, 7, 0]
    radius_speed_accel: [1, 1, 1]
    map_name: conveyor_map
    localizer_main_sub: [1, 0]
    storage_level_unload_load:
      - [100, 100]
  - id: 202
    type: 0
    pose: [29, 7, 0]
    radius_speed_accel: [1, 1, 1]
    map_name: conveyor_map
    localizer_main_sub: [1, 0]
    storage_level_unload_load:
      - [100, 100]
  - id: 203
    type: 0
    pose: [24, 7, 0]
    radius_speed_accel: [1, 1, 1]
    map_name: conveyor_map
    localizer_main_sub: [1, 0]
    storage_level_unload_load:
      - [100, 100]
  - id: 204
    type: 0
    pose: [23.5, 6.5, 0]
    radius_speed_accel: [1, 1, 1]
    map_name: conveyor_map
    localizer_main_sub: [1, 0]
    storage_level_unload_load:
      - [100, 100]
  - id: 205
    type: 0
    pose: [23, 6, 0]
    radius_speed_accel: [1, 1, 1]
    map_name: conveyor_map
    localizer_main_sub: [1, 0]
    storage_level_unload_load:
      - [100, 100]
  - id: 206
    type: 0
    pose: [21.5, 4.5, 0]
    radius_speed_accel: [1, 1, 1]
    map_name: conveyor_map
    localizer_main_sub: [1, 0]
    storage_level_unload_load:
      - [100, 100]
  - id: 207
    type: 0
    pose: [20, 3, 0]
    radius_speed_accel: [1, 1, 1]
    map_name: conveyor_map
    localizer_main_sub: [1, 0]
    storage_level_unload_load:
      - [100, 100]
  - id: 208
    type: 0
    pose: [19.5, 2.5, 0]
    radius_speed_accel: [1, 1, 1]
    map_name: conveyor_map
    localizer_main_sub: [1, 0]
    storage_level_unload_load:
      - [100, 100]
  - id: 209
    type: 0
    pose: [19, 2, 0]
    radius_speed_accel: [1, 1, 1]
    map_name: conveyor_map
    localizer_main_sub: [1, 0]
    storage_level_unload_load:
      - [100, 100]
  - id: 210
    type: 0
    pose: [19, 7, 0]
    radius_speed_accel: [1, 1, 1]
    map_name: conveyor_map
    localizer_main_sub: [1, 0]
    storage_level_unload_load:
      - [100, 100]
  - id: 211
    type: 0
    pose: [18.5, 11.5, 0]
    radius_speed_accel: [1, 1, 1]
    map_name: conveyor_map
    localizer_main_sub: [1, 0]
    storage_level_unload_load:
      - [100, 100]
  - id: 212
    type: 0
    pose: [18, 11, 0]
    radius_speed_accel: [1, 1, 1]
    map_name: conveyor_map
    localizer_main_sub: [1, 0]
    storage_level_unload_load:
      - [100, 100]
  - id: 213
    type: 0
    pose: [16.5, 9.5, 0]
    radius_speed_accel: [1, 1, 1]
    map_name: conveyor_map
    localizer_main_sub: [1, 0]
    storage_level_unload_load:
      - [100, 100]
  - id: 214
    type: 0
    pose: [15, 8, 0]
    radius_speed_accel: [1, 1, 1]
    map_name: conveyor_map
    localizer_main_sub: [1, 0]
    storage_level_unload_load:
      - [100, 100]
  - id: 215
    type: 0
    pose: [14.5, 7.5, 0]
    radius_speed_accel: [1, 1, 1]
    map_name: conveyor_map
    localizer_main_sub: [1, 0]
    storage_level_unload_load:
      - [100, 100]
  - id: 216
    type: 0
    pose: [14, 7, 0]
    radius_speed_accel: [1, 1, 1]
    map_name: conveyor_map
    localizer_main_sub: [1, 0]
    storage_level_unload_load:
      - [100, 100]
  - id: 217
    type: 0
    pose: [14, 6.5, 0]
    radius_speed_accel: [1, 1, 1]
    map_name: conveyor_map
    localizer_main_sub: [1, 0]
    storage_level_unload_load:
      - [100, 100]
  - id: 218
    type: 0
    pose: [14, 6, 0]
    radius_speed_accel: [1, 1, 1]
    map_name: conveyor_map
    localizer_main_sub: [1, 0]
    storage_level_unload_load:
      - [100, 100]
  - id: 219
    type: 0
    pose: [14, 4.5, 0]
    radius_speed_accel: [1, 1, 1]
    map_name: conveyor_map
    localizer_main_sub: [1, 0]
    storage_level_unload_load:
      - [100, 100]
  - id: 220
    type: 0
    pose: [14, 3, 0]
    radius_speed_accel: [1, 1, 1]
    map_name: conveyor_map
    localizer_main_sub: [1, 0]
    storage_level_unload_load:
      - [100, 100]
  - id: 221
    type: 0
    pose: [14, 2.5, 0]
    radius_speed_accel: [1, 1, 1]
    map_name: conveyor_map
    localizer_main_sub: [1, 0]
    storage_level_unload_load:
      - [100, 100]
  - id: 222
    type: 0
    pose: [14, 2, 0]
    radius_speed_accel: [1, 1, 1]
    map_name: conveyor_map
    localizer_main_sub: [1, 0]
    storage_level_unload_load:
      - [100, 100]
  - id: 223
    type: 0
    pose: [9, 11.5, 0]
    radius_speed_accel: [1, 1, 1]
    map_name: conveyor_map
    localizer_main_sub: [1, 0]
    storage_level_unload_load:
      - [100, 100]
  - id: 224
    type: 0
    pose: [9, 11, 0]
    radius_speed_accel: [1, 1, 1]
    map_name: conveyor_map
    localizer_main_sub: [1, 0]
    storage_level_unload_load:
      - [100, 100]
  - id: 225
    type: 0
    pose: [9, 9.5, 0]
    radius_speed_accel: [1, 1, 1]
    map_name: conveyor_map
    localizer_main_sub: [1, 0]
    storage_level_unload_load:
      - [100, 100]
  - id: 226
    type: 0
    pose: [9, 8, 0]
    radius_speed_accel: [1, 1, 1]
    map_name: conveyor_map
    localizer_main_sub: [1, 0]
    storage_level_unload_load:
      - [100, 100]
  - id: 227
    type: 0
    pose: [9, 7.5, 0]
    radius_speed_accel: [1, 1, 1]
    map_name: conveyor_map
    localizer_main_sub: [1, 0]
    storage_level_unload_load:
      - [100, 100]
  - id: 228
    type: 0
    pose: [9, 7, 0]
    radius_speed_accel: [1, 1, 1]
    map_name: conveyor_map
    localizer_main_sub: [1, 0]
    storage_level_unload_load:
      - [100, 100]
  - id: 229
    type: 0
    pose: [9, 2, 0]
    radius_speed_accel: [1, 1, 1]
    map_name: conveyor_map
    localizer_main_sub: [1, 0]
    storage_level_unload_load:
      - [100, 100]
  - id: 230
    type: 0
    pose: [5, 7, 0]
    radius_speed_accel: [1, 1, 1]
    map_name: conveyor_map
    localizer_main_sub: [1, 0]
    storage_level_unload_load:
      - [100, 100]
  - id: 231
    type: 0
    pose: [2, 7, 0]
    radius_speed_accel: [1, 1, 1]
    map_name: conveyor_map
    localizer_main_sub: [1, 0]
    storage_level_unload_load:
      - [100, 100]