total_number: 10
list:
  - id: 1
    type: 1
    pose: [1.5, 5, 0]
    radius_speed_accel: [0.1, 0.35, 0.35]
    map_name: conveyor_map
    localizer_main_sub: [1, 0]
    storage_level_unload_load:
      - [100, 100]
  - id: 2
    type: 0
    pose: [1.5, 6, 0]
    radius_speed_accel: [0.5, 0.35, 0.35]
    map_name: conveyor_map
    localizer_main_sub: [1, 0]
    storage_level_unload_load:
      - [100, 100]
  - id: 3
    type: 2
    pose: [6, 6, 0]
    radius_speed_accel: [0.7, 0.35, 0.35]
    map_name: conveyor_map
    localizer_main_sub: [1, 0]
    storage_level_unload_load:
      - [100, 100]
  - id: 4
    type: 1
    pose: [6, 8, 0]
    radius_speed_accel: [0, 0.35, 0.35]
    map_name: conveyor_map
    localizer_main_sub: [1, 0]
    storage_level_unload_load:
      - [100, 100]
  - id: 5
    type: 0
    pose: [4, 11, 0]
    radius_speed_accel: [0.7, 0.2, 0.35]
    map_name: conveyor_map
    localizer_main_sub: [1, 0]
    storage_level_unload_load:
      - [100, 100]
  - id: 6
    type: 0
    pose: [1.5, 11, 0]
    radius_speed_accel: [0.7, 0.35, 0.35]
    map_name: conveyor_map
    localizer_main_sub: [1, 0]
    storage_level_unload_load:
      - [100, 100]
  - id: 7
    type: 0
    pose: [1.5, 14, 0]
    radius_speed_accel: [0.2, 0.35, 0.35]
    map_name: conveyor_map
    localizer_main_sub: [1, 0]
    storage_level_unload_load:
      - [100, 100]
  - id: 8
    type: 2
    pose: [4, 14, 0]
    radius_speed_accel: [0.7, 0.35, 0.35]
    map_name: conveyor_map
    localizer_main_sub: [1, 0]
    storage_level_unload_load:
      - [100, 100]
  - id: 9
    type: 1
    pose: [6, 14, 0]
    radius_speed_accel: [0.3, 0.35, 0.35]
    map_name: conveyor_map
    localizer_main_sub: [1, 0]
    storage_level_unload_load:
      - [100, 100]
  - id: 10
    type: 1
    pose: [1.5, 15, 0]
    radius_speed_accel: [0, 0.35, 0.35]
    map_name: conveyor_map
    localizer_main_sub: [1, 0]
    storage_level_unload_load:
      - [100, 100]
