node_groups:
  - name: "loading_zone"
    nodes: [10, 9, 8, 7]
  - name: "unloading_zone"
    nodes: [20, 19,16,18,15,17]
  - name: "parking_zone"
    nodes: [3,2,13,12]
  - name: "test_zone"
    nodes: [101,1028,1026]
