scenario:
  - task_type: "inbound"
    from_location: "20"
    to_location: "19"
  - task_type: "inbound"
    from_location: "13"
    to_location: "12"
  - task_type: "inbound"
    from_location: "3"
    to_location: "2"
  - task_type: "outbound"
    from_location: "10"
    to_location: "9"
  - task_type: "inbound"
    from_location: "10"
    to_location: "7"
