total_number: 36
list:
  - id_from_to: [1031, 1033]
    accel_speed: [0.4, 1]
    motion: 1
    dof: 1
    safety_zone: 1
    enable_sensors: 15
    cost_time: 0
  - id_from_to: [1033, 1007]
    accel_speed: [0.4, 1]
    motion: 1
    dof: 1
    safety_zone: 1
    enable_sensors: 15
    cost_time: 0
  - id_from_to: [1015, 1041]
    accel_speed: [0.11, 0.2]
    motion: 1
    dof: 1
    safety_zone: 1
    enable_sensors: 15
    cost_time: 0
  - id_from_to: [1041, 1039]
    accel_speed: [0.1, 0.2]
    motion: 1
    dof: 1
    safety_zone: 1
    enable_sensors: 15
    cost_time: 0
  - id_from_to: [1039, 1041]
    accel_speed: [0.1, -0.2]
    motion: 1
    dof: 1
    safety_zone: 1
    enable_sensors: 15
    cost_time: 0
  - id_from_to: [1041, 1015]
    accel_speed: [0.1, 0.2]
    motion: 1
    dof: 1
    safety_zone: 1
    enable_sensors: 15
    cost_time: 0
  - id_from_to: [1019, 1035]
    accel_speed: [0.1, 0.2]
    motion: 1
    dof: 1
    safety_zone: 1
    enable_sensors: 15
    cost_time: 0
  - id_from_to: [1035, 1037]
    accel_speed: [0.1, 0.2]
    motion: 1
    dof: 1
    safety_zone: 1
    enable_sensors: 15
    cost_time: 0
  - id_from_to: [1037, 1035]
    accel_speed: [0.1, -0.2]
    motion: 1
    dof: 1
    safety_zone: 1
    enable_sensors: 15
    cost_time: 0
  - id_from_to: [1035, 1019]
    accel_speed: [0.1, 0.2]
    motion: 1
    dof: 1
    safety_zone: 1
    enable_sensors: 15
    cost_time: 0
  - id_from_to: [1002, 1000]
    accel_speed: [0.2, 0.3]
    motion: 1
    dof: 1
    safety_zone: 1
    enable_sensors: 15
    cost_time: 0
  - id_from_to: [1000, 1014]
    accel_speed: [0.2, 0.3]
    motion: 1
    dof: 1
    safety_zone: 1
    enable_sensors: 15
    cost_time: 0
  - id_from_to: [1014, 1012]
    accel_speed: [0.2, 0.3]
    motion: 1
    dof: 1
    safety_zone: 1
    enable_sensors: 15
    cost_time: 0
  - id_from_to: [1012, 1010]
    accel_speed: [0.2, 0.3]
    motion: 1
    dof: 1
    safety_zone: 1
    enable_sensors: 15
    cost_time: 0
  - id_from_to: [1010, 1008]
    accel_speed: [0.2, 0.3]
    motion: 1
    dof: 1
    safety_zone: 1
    enable_sensors: 15
    cost_time: 0
  - id_from_to: [1008, 1006]
    accel_speed: [0.2, 0.3]
    motion: 1
    dof: 1
    safety_zone: 1
    enable_sensors: 15
    cost_time: 0
  - id_from_to: [1006, 1004]
    accel_speed: [0.2, 0.3]
    motion: 1
    dof: 1
    safety_zone: 1
    enable_sensors: 15
    cost_time: 0
  - id_from_to: [1004, 1002]
    accel_speed: [0.2, 0.3]
    motion: 1
    dof: 1
    safety_zone: 1
    enable_sensors: 15
    cost_time: 0
  - id_from_to: [1008, 1013]
    accel_speed: [0.35, 0.5]
    motion: 1
    dof: 1
    safety_zone: 1
    enable_sensors: 15
    cost_time: 0
  - id_from_to: [1013, 1008]
    accel_speed: [0.35, 0.5]
    motion: 1
    dof: 1
    safety_zone: 1
    enable_sensors: 15
    cost_time: 0
  - id_from_to: [1007, 1005]
    accel_speed: [0.4, 1]
    motion: 1
    dof: 1
    safety_zone: 1
    enable_sensors: 15
    cost_time: 0
  - id_from_to: [1005, 1003]
    accel_speed: [0.4, 1]
    motion: 1
    dof: 1
    safety_zone: 1
    enable_sensors: 15
    cost_time: 0
  - id_from_to: [1003, 1001]
    accel_speed: [0.4, 0.7]
    motion: 1
    dof: 1
    safety_zone: 1
    enable_sensors: 15
    cost_time: 0
  - id_from_to: [1025, 1047]
    accel_speed: [0.2, 0.5]
    motion: 1
    dof: 1
    safety_zone: 1
    enable_sensors: 15
    cost_time: 0
  - id_from_to: [1047, 1027]
    accel_speed: [0.2, 0.5]
    motion: 1
    dof: 1
    safety_zone: 1
    enable_sensors: 15
    cost_time: 0
  - id_from_to: [1027, 1031]
    accel_speed: [0.2, 0.5]
    motion: 1
    dof: 1
    safety_zone: 1
    enable_sensors: 15
    cost_time: 0
  - id_from_to: [1001, 1023]
    accel_speed: [0.2, 0.5]
    motion: 1
    dof: 1
    safety_zone: 1
    enable_sensors: 15
    cost_time: 0
  - id_from_to: [1023, 1021]
    accel_speed: [0.2, 0.5]
    motion: 1
    dof: 1
    safety_zone: 1
    enable_sensors: 15
    cost_time: 0
  - id_from_to: [1021, 1019]
    accel_speed: [0.2, 0.5]
    motion: 1
    dof: 1
    safety_zone: 1
    enable_sensors: 15
    cost_time: 0
  - id_from_to: [1019, 1017]
    accel_speed: [0.2, 0.5]
    motion: 1
    dof: 1
    safety_zone: 1
    enable_sensors: 15
    cost_time: 0
  - id_from_to: [1017, 1015]
    accel_speed: [0.2, 0.5]
    motion: 1
    dof: 1
    safety_zone: 1
    enable_sensors: 15
    cost_time: 0
  - id_from_to: [1015, 1013]
    accel_speed: [0.2, 0.5]
    motion: 1
    dof: 1
    safety_zone: 1
    enable_sensors: 15
    cost_time: 0
  - id_from_to: [1013, 1011]
    accel_speed: [0.2, 0.5]
    motion: 1
    dof: 1
    safety_zone: 1
    enable_sensors: 15
    cost_time: 0
  - id_from_to: [1011, 1009]
    accel_speed: [0.2, 0.5]
    motion: 1
    dof: 1
    safety_zone: 1
    enable_sensors: 15
    cost_time: 0
  - id_from_to: [1009, 1007]
    accel_speed: [0.2, 0.5]
    motion: 1
    dof: 1
    safety_zone: 1
    enable_sensors: 15
    cost_time: 0
  - id_from_to: [1011, 1025]
    accel_speed: [0.4, 0.5]
    motion: 1
    dof: 1
    safety_zone: 1
    enable_sensors: 15
    cost_time: 0
