total_number: 32
list:
  - id: 21
    type: 0
    pose: [6.5, 13, 0]
    radius_speed_accel: [1, 1, 1]
    map_name: conveyor_map
    localizer_main_sub: [1, 0]
    storage_level_unload_load:
      - [100, 100]
  - id: 1000
    type: 0
    pose: [3.02, 6.25, 0]
    radius_speed_accel: [0.2, 0.1, 0.3]
    map_name: conveyor_map
    localizer_main_sub: [1, 0]
    storage_level_unload_load:
      - [100, 100]
  - id: 1001
    type: 0
    pose: [1.7, 4.9, 0]
    radius_speed_accel: [0.1, 0.3, 0.35]
    map_name: conveyor_map
    localizer_main_sub: [1, 0]
    storage_level_unload_load:
      - [100, 100]
  - id: 1002
    type: 2
    pose: [3.02, 7.84, 0]
    radius_speed_accel: [0, 0.3, 0.2]
    map_name: conveyor_map
    localizer_main_sub: [1, 0]
    storage_level_unload_load:
      - [100, 100]
  - id: 1003
    type: 1
    pose: [1.7, 6.9, 0]
    radius_speed_accel: [0, 1, 0.35]
    map_name: conveyor_map
    localizer_main_sub: [1, 0]
    storage_level_unload_load:
      - [100, 100]
  - id: 1004
    type: 0
    pose: [3.02, 9.4, 0]
    radius_speed_accel: [0.2, 0.1, 1]
    map_name: conveyor_map
    localizer_main_sub: [1, 0]
    storage_level_unload_load:
      - [100, 100]
  - id: 1005
    type: 0
    pose: [1.7, 8.9, 0]
    radius_speed_accel: [0, 1, 0.35]
    map_name: conveyor_map
    localizer_main_sub: [1, 0]
    storage_level_unload_load:
      - [100, 100]
  - id: 1006
    type: 1
    pose: [4.02, 9.4, 0]
    radius_speed_accel: [0, 0.3, 0.2]
    map_name: lr_demo
    localizer_main_sub: [1, 0]
    storage_level_unload_load:
      - [100, 100]
  - id: 1007
    type: 0
    pose: [1.7, 11, 0]
    radius_speed_accel: [1, 1, 0.35]
    map_name: conveyor_map
    localizer_main_sub: [1, 0]
    storage_level_unload_load:
      - [100, 100]
  - id: 1008
    type: 0
    pose: [5.15, 9.4, 0]
    radius_speed_accel: [0.2, 0.1, 1]
    map_name: conveyor_map
    localizer_main_sub: [1, 0]
    storage_level_unload_load:
      - [100, 100]
  - id: 1009
    type: 0
    pose: [3.4, 11, 0]
    radius_speed_accel: [0, 1, 0.35]
    map_name: conveyor_map
    localizer_main_sub: [1, 0]
    storage_level_unload_load:
      - [100, 100]
  - id: 1010
    type: 3
    pose: [5.15, 7.84, 0]
    radius_speed_accel: [0, 0.3, 0.1]
    map_name: conveyor_map
    localizer_main_sub: [1, 0]
    storage_level_unload_load:
      - [100, 100]
  - id: 1011
    type: 0
    pose: [5, 11, 0]
    radius_speed_accel: [0, 0.5, 1]
    map_name: conveyor_map
    localizer_main_sub: [1, 0]
    storage_level_unload_load:
      - [100, 100]
  - id: 1012
    type: 0
    pose: [5.15, 6.25, 0]
    radius_speed_accel: [0.2, 0.1, 0.35]
    map_name: conveyor_map
    localizer_main_sub: [1, 0]
    storage_level_unload_load:
      - [100, 100]
  - id: 1013
    type: 0
    pose: [6.5, 11, 0]
    radius_speed_accel: [1, 0.3, 0.35]
    map_name: conveyor_map
    localizer_main_sub: [1, 0]
    storage_level_unload_load:
      - [100, 100]
  - id: 1014
    type: 1
    pose: [4.02, 6.25, 0]
    radius_speed_accel: [0, 0.3, 0.2]
    map_name: lr_demo
    localizer_main_sub: [1, 0]
    storage_level_unload_load:
      - [100, 100]
  - id: 1015
    type: 0
    pose: [6.5, 8.9, 0]
    radius_speed_accel: [0.3, 0.1, 0.35]
    map_name: conveyor_map
    localizer_main_sub: [1, 0]
    storage_level_unload_load:
      - [100, 100]
  - id: 1017
    type: 0
    pose: [6.5, 6.9, 0]
    radius_speed_accel: [0, 0.5, 1]
    map_name: conveyor_map
    localizer_main_sub: [1, 0]
    storage_level_unload_load:
      - [100, 100]
  - id: 1019
    type: 0
    pose: [6.5, 4.9, 0]
    radius_speed_accel: [0.35, 0.3, 0.35]
    map_name: conveyor_map
    localizer_main_sub: [1, 0]
    storage_level_unload_load:
      - [100, 100]
  - id: 1021
    type: 0
    pose: [5, 4.9, 0]
    radius_speed_accel: [0, 1, 1]
    map_name: conveyor_map
    localizer_main_sub: [1, 0]
    storage_level_unload_load:
      - [100, 100]
  - id: 1023
    type: 0
    pose: [3.4, 4.9, 0]
    radius_speed_accel: [0, 1, 1]
    map_name: conveyor_map
    localizer_main_sub: [1, 0]
    storage_level_unload_load:
      - [100, 100]
  - id: 1025
    type: 0
    pose: [5, 12.7, 0]
    radius_speed_accel: [0, 0.7, 0.3]
    map_name: conveyor_map
    localizer_main_sub: [1, 0]
    storage_level_unload_load:
      - [100, 100]
  - id: 1027
    type: 2
    pose: [3.28, 14.5, 0]
    radius_speed_accel: [0, 0.7, 0.3]
    map_name: conveyor_map
    localizer_main_sub: [1, 0]
    storage_level_unload_load:
      - [100, 100]
  - id: 1029
    type: 0
    pose: [1.7, 16.5, 0]
    radius_speed_accel: [0.35, 0.7, 0.3]
    map_name: conveyor_map
    localizer_main_sub: [1, 0]
    storage_level_unload_load:
      - [100, 100]
  - id: 1031
    type: 0
    pose: [1.7, 14.5, 0]
    radius_speed_accel: [0, 1, 0.4]
    map_name: conveyor_map
    localizer_main_sub: [1, 0]
    storage_level_unload_load:
      - [100, 100]
  - id: 1033
    type: 0
    pose: [1.7, 12.7, 0]
    radius_speed_accel: [0, 1, 0.4]
    map_name: conveyor_map
    localizer_main_sub: [1, 0]
    storage_level_unload_load:
      - [100, 100]
  - id: 1035
    type: 0
    pose: [7.3, 4.9, 0]
    radius_speed_accel: [0.2, 0.1, 0.3]
    map_name: conveyor_map
    localizer_main_sub: [1, 0]
    storage_level_unload_load:
      - [100, 100]
  - id: 1037
    type: 2
    pose: [7.3, 3.6, 0]
    radius_speed_accel: [0, 0.3, 0.3]
    map_name: conveyor_map
    localizer_main_sub: [1, 0]
    storage_level_unload_load:
      - [100, 100]
  - id: 1039
    type: 2
    pose: [7.5, 7.6, 0]
    radius_speed_accel: [0, 0.3, 0.3]
    map_name: conveyor_map
    localizer_main_sub: [1, 0]
    storage_level_unload_load:
      - [100, 100]
  - id: 1041
    type: 0
    pose: [7.5, 8.9, 0]
    radius_speed_accel: [0.35, 0.1, 0.35]
    map_name: conveyor_map
    localizer_main_sub: [1, 0]
    storage_level_unload_load:
      - [100, 100]
  - id: 1043
    type: 3
    pose: [2.45, 15.55, 0]
    radius_speed_accel: [0, 0.7, 0.3]
    map_name: conveyor_map
    localizer_main_sub: [1, 0]
    storage_level_unload_load:
      - [100, 100]
  - id: 1047
    type: 1
    pose: [4.17, 13.52, 0]
    radius_speed_accel: [0, 0.7, 0.3]
    map_name: conveyor_map
    localizer_main_sub: [1, 0]
    storage_level_unload_load:
      - [100, 100]
