total_number: 30
list:
  - id: 21
    type: 0
    pose: [6.5, 13, 0]
    radius_speed_accel: [1, 1, 1]
    map_name: conveyor_map
    localizer_main_sub: [1, 0]
    storage_level_unload_load:
      - [100, 100]
  - id: 1000
    type: 0
    pose: [3.02, 6.48, 0]
    radius_speed_accel: [0.2, 0.1, 0.3]
    map_name: conveyor_map
    localizer_main_sub: [1, 0]
    storage_level_unload_load:
      - [100, 100]
  - id: 1001
    type: 1
    pose: [1.66, 5.15, 0]
    radius_speed_accel: [0.4, 0.25, 0.35]
    map_name: conveyor_map
    localizer_main_sub: [1, 0]
    storage_level_unload_load:
      - [100, 100]
  - id: 1002
    type: 2
    pose: [3.02, 7.6, 0]
    radius_speed_accel: [0, 0.3, 0.2]
    map_name: conveyor_map
    localizer_main_sub: [1, 0]
    storage_level_unload_load:
      - [100, 100]
  - id: 1003
    type: 1
    pose: [1.66, 6.9, 0]
    radius_speed_accel: [0, 1, 0.35]
    map_name: conveyor_map
    localizer_main_sub: [1, 0]
    storage_level_unload_load:
      - [100, 100]
  - id: 1004
    type: 0
    pose: [3.02, 8.67, 0]
    radius_speed_accel: [0.2, 0.1, 1]
    map_name: conveyor_map
    localizer_main_sub: [1, 0]
    storage_level_unload_load:
      - [100, 100]
  - id: 1005
    type: 0
    pose: [1.66, 8.55, 0]
    radius_speed_accel: [0, 1, 0.35]
    map_name: conveyor_map
    localizer_main_sub: [1, 0]
    storage_level_unload_load:
      - [100, 100]
  - id: 1006
    type: 1
    pose: [3.94, 8.66, 0]
    radius_speed_accel: [0, 0.3, 0.2]
    map_name: conveyor_map
    localizer_main_sub: [1, 0]
    storage_level_unload_load:
      - [100, 100]
  - id: 1007
    type: 1
    pose: [1.66, 10, 0]
    radius_speed_accel: [0.35, 0.35, 0.35]
    map_name: conveyor_map
    localizer_main_sub: [1, 0]
    storage_level_unload_load:
      - [100, 100]
  - id: 1008
    type: 0
    pose: [5.15, 8.67, 0]
    radius_speed_accel: [0.2, 0.1, 1]
    map_name: conveyor_map
    localizer_main_sub: [1, 0]
    storage_level_unload_load:
      - [100, 100]
  - id: 1009
    type: 3
    pose: [3.4, 10, 0]
    radius_speed_accel: [0, 1, 0.35]
    map_name: conveyor_map
    localizer_main_sub: [1, 0]
    storage_level_unload_load:
      - [100, 100]
  - id: 1010
    type: 0
    pose: [5.15, 7.6, 0]
    radius_speed_accel: [0, 0.3, 0.1]
    map_name: conveyor_map
    localizer_main_sub: [1, 0]
    storage_level_unload_load:
      - [100, 100]
  - id: 1011
    type: 0
    pose: [5, 10, 0]
    radius_speed_accel: [0.5, 0.5, 1]
    map_name: conveyor_map
    localizer_main_sub: [1, 0]
    storage_level_unload_load:
      - [100, 100]
  - id: 1012
    type: 0
    pose: [5.15, 6.48, 0]
    radius_speed_accel: [0.2, 0.1, 0.35]
    map_name: conveyor_map
    localizer_main_sub: [1, 0]
    storage_level_unload_load:
      - [100, 100]
  - id: 1013
    type: 0
    pose: [6.5, 10, 0]
    radius_speed_accel: [0.35, 0.35, 0.35]
    map_name: conveyor_map
    localizer_main_sub: [1, 0]
    storage_level_unload_load:
      - [100, 100]
  - id: 1014
    type: 1
    pose: [4.35, 6.5, 0]
    radius_speed_accel: [0, 0.3, 0.2]
    map_name: conveyor_map
    localizer_main_sub: [1, 0]
    storage_level_unload_load:
      - [100, 100]
  - id: 1015
    type: 1
    pose: [6.5, 8.9, 0]
    radius_speed_accel: [0.5, 0.3, 0.35]
    map_name: conveyor_map
    localizer_main_sub: [1, 0]
    storage_level_unload_load:
      - [100, 100]
  - id: 1017
    type: 0
    pose: [6.5, 6.9, 0]
    radius_speed_accel: [0.5, 0.5, 1]
    map_name: conveyor_map
    localizer_main_sub: [1, 0]
    storage_level_unload_load:
      - [100, 100]
  - id: 1019
    type: 0
    pose: [6.5, 5.15, 0]
    radius_speed_accel: [0.35, 0.35, 0.35]
    map_name: conveyor_map
    localizer_main_sub: [1, 0]
    storage_level_unload_load:
      - [100, 100]
  - id: 1021
    type: 0
    pose: [5, 5.15, 0]
    radius_speed_accel: [1, 0.5, 1]
    map_name: conveyor_map
    localizer_main_sub: [1, 0]
    storage_level_unload_load:
      - [100, 100]
  - id: 1023
    type: 3
    pose: [3.4, 5.15, 0]
    radius_speed_accel: [0, 1, 1]
    map_name: conveyor_map
    localizer_main_sub: [1, 0]
    storage_level_unload_load:
      - [100, 100]
  - id: 1025
    type: 1
    pose: [5, 12.7, 0]
    radius_speed_accel: [0.5, 0.7, 0.3]
    map_name: conveyor_map
    localizer_main_sub: [1, 0]
    storage_level_unload_load:
      - [100, 100]
  - id: 1027
    type: 2
    pose: [3.28, 14.5, 0]
    radius_speed_accel: [0.5, 0.35, 0.3]
    map_name: conveyor_map
    localizer_main_sub: [1, 0]
    storage_level_unload_load:
      - [100, 100]
  - id: 1031
    type: 0
    pose: [1.66, 14.5, 0]
    radius_speed_accel: [0.5, 0.35, 0.3]
    map_name: conveyor_map
    localizer_main_sub: [1, 0]
    storage_level_unload_load:
      - [100, 100]
  - id: 1033
    type: 0
    pose: [1.66, 12.7, 0]
    radius_speed_accel: [0, 1, 0.4]
    map_name: conveyor_map
    localizer_main_sub: [1, 0]
    storage_level_unload_load:
      - [100, 100]
  - id: 1035
    type: 0
    pose: [7.3, 4.7, 0]
    radius_speed_accel: [0.2, 0.1, 0.3]
    map_name: conveyor_map
    localizer_main_sub: [1, 0]
    storage_level_unload_load:
      - [100, 100]
  - id: 1037
    type: 2
    pose: [7.3, 3.6, 0]
    radius_speed_accel: [0, 0.3, 0.3]
    map_name: conveyor_map
    localizer_main_sub: [1, 0]
    storage_level_unload_load:
      - [100, 100]
  - id: 1039
    type: 2
    pose: [7.5, 7.6, 0]
    radius_speed_accel: [0, 0.3, 0.3]
    map_name: conveyor_map
    localizer_main_sub: [1, 0]
    storage_level_unload_load:
      - [100, 100]
  - id: 1041
    type: 0
    pose: [7.5, 8.9, 0]
    radius_speed_accel: [0.35, 0.1, 0.35]
    map_name: conveyor_map
    localizer_main_sub: [1, 0]
    storage_level_unload_load:
      - [100, 100]
  - id: 1047
    type: 3
    pose: [4.17, 13.52, 0]
    radius_speed_accel: [0, 0.7, 0.3]
    map_name: conveyor_map
    localizer_main_sub: [1, 0]
    storage_level_unload_load:
      - [100, 100]
