






node_bound:
  minimum: 0.020 # m
  maximum: 0.150 # m
  parity:  0.005 # m

approach_destination:
  speed:             0.10 # m/s
  distance_complete: 0.15 # m
  radius:            0.10 # m

motion:
  reference_angle:
    straight: 0.0
    curve: 45.0
  threshold_angle:
    straight: 15.0    # °
    curve: 20.0       # °
    inverse: 170.0    # °
  threshold_error:
    normal: 0.3
    angle: 5.0

  speed_low: 0.3
  speed_high: 0.8
  gain_set:
    normal:
      speed_low: 4.0    # 8.0
      speed_high: 0.5   # 0.5
    angle:
      speed_low: 0.8    # 1.0
      speed_high: 2.1   # 2.1

  speed_rotation: 15 # °/s
  protection_overshoot: 0.85  
