node_groups:
  - name: "loading_zone_1"
    nodes: [2,3,4,5,6,7,10,11,12,13,14,15]
  - name: "loading_zone_2"
    nodes: [18,19,20,21,22,23,24,25,27,28,29,30,31,32,33,34]
  - name: "loading_zone_3"
    nodes: [55,56,57,58,59,60]
  - name: "unloading_zone"
    nodes: [43,44,45,46,47,48]
  - name: "unloading_zone2"
    nodes: [49,50,51,52,53,54]
  - name: "unloading_zone3"
    nodes: [35,36,37,38,40,41,42]
  - name: "parking_zone_1"
    nodes: [208,207]
  - name: "parking_zone_2"
    nodes: [208,207]
  - name: "parking_zone_3"
    nodes: [203,204]
  - name: "parking_zone_4"
    nodes: [205,206]
