######################################
# left motor 0번으로 는 cw 방향일 때 엔코더 +값이 나와야 한다.
#
######################################

comms:
  address: /dev/pcanusb32
  id:
    left: 1
    right: 2


######################################
#
######################################
mechanical:
  gear_ratio: 10


######################################
# direction
# 0 : forward
# 1 : reverse
######################################
motors:
  left:
    count_per_revolution: 10000
    direction: 0
  right:
    count_per_revolution: 10000
    direction: 1

