device: /dev/input/js0
thread period: 5                    # ms
type: 2                             # xbox : 0, sn30pro : 1 
                                    # 8bitdo ultimate2 : 2, xbox_wire : 3
                                    # 버튼은 xbox 기준으로 통일
reconnectoring period: 1000         #ms

